services:
  - type: web
    name: sih26077-weather-nowcaster
    runtime: docker
    plan: free
    region: singapore
    branch: master
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: STREAMLIT_SERVER_FILE_WATCHER_TYPE
        value: none
