[theme]
primaryColor = "#00d2ff"
backgroundColor = "#0b111e"
secondaryBackgroundColor = "#131d2f"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
