[theme]
base = "light"
primaryColor = "#0284c7"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = false
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
